-- CREATE DATABASE HI_COUPON_DB
-- GO

USE HI_COUPON_DB
GO

CREATE TABLE [USER] (
    USER_ID INT PRIMARY KEY IDENTITY,
    [NAME] NVARCHAR(25) NOT NULL,
    LAST_NAME NVARCHAR(50) NOT NULL,
    IDENTIFICATION_CARD NVARCHAR(20) NOT NULL UNIQUE,
    DATE_BIRTH DATE NOT NULL,
    EMAIL NVARCHAR(50) NOT NULL UNIQUE,
    [PASSWORD] NVARCHAR(12) NOT NULL
)

CREATE TABLE BILL (
    BILL_ID INT  PRIMARY KEY IDENTITY,
    USER_ID INT NOT NULL,
    BASE_PRICE DECIMAL(10, 2) NOT NULL,
    IVA DECIMAL(10, 2) NOT NULL,
    TOTAL DECIMAL(10, 2) NOT NULL,
    CONSTRAINT FK_USER_FOR_BILL FOREIGN KEY (USER_ID) REFERENCES [USER](USER_ID)
)

CREATE TABLE BILL_COUPON (
    BILL_COUPON_ID INT PRIMARY KEY IDENTITY,
    BILL_ID INT NOT NULL,
    COUPON_ID INT NOT NULL,
    QUANTITY INT NOT NULL CHECK(QUANTITY > 0),
    CONSTRAINT FK_BILL_FOR_BILL_COUPON FOREIGN KEY (BILL_ID) REFERENCES BILL(BILL_ID)
)

